# Generated by Django 6.0.4 on 2026-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(max_length=100)),
                ('host_institution', models.CharField(blank=True, max_length=255)),
                ('host_country', models.CharField(blank=True, max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('fully_funded', models.BooleanField(default=False)),
                ('what_it_covers', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('application_link', models.URLField(blank=True, max_length=500)),
                ('open_date', models.CharField(blank=True, max_length=150)),
                ('deadline', models.CharField(blank=True, max_length=150)),
                ('source_website', models.URLField(blank=True, max_length=500)),
                ('language_requirements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_verified', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-fully_funded', 'name'],
            },
        ),
    ]
