# Generated by Django 6.0.4 on 2026-04-19 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(help_text='Your CGPA out of 4.0')),
                ('degree_level', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=50)),
                ('field_of_study', models.CharField(max_length=150)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('language_cert', models.CharField(blank=True, choices=[('', 'None'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('Duolingo', 'Duolingo English Test'), ('PTE', 'PTE Academic')], default='', max_length=50)),
                ('language_score', models.FloatField(blank=True, null=True)),
                ('preferred_country', models.CharField(blank=True, max_length=100)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
